In [1]:
import pandas as pd

final_data = "../results/final_housing_data.csv"
df = pd.read_csv(final_data)

In [ ]:
# explore ranking of Carver Cluster schools by percentage of students with housing concerns
df_ranked = df.sort_values(by="percent_housing_concern", ascending=False, ignore_index=True)
display(df_ranked)

,school,file,housing_concern_count,total_students,percent_housing_concern
0,Michael R. Hollis Innovation Academy,761 - Michael R. Hollis Innovation Academy.xls,20,172,11.627907
1,Hillside Conant School,761 - Hillside Conant School.xls,9,83,10.843373
2,Judson Price Middle School,761 - Judson Price Middle School.xls,24,227,10.572687
3,The Kindezi School,761 - The Kindezi School.xls,12,115,10.434783
4,Centennial Place Academy (Charter),761 - Centennial Place Academy _Charter_.xls,21,202,10.396040
5,Coretta Scott King Young Women's Leadership Ac...,761 - Coretta Scott King Young Women_s Leaders...,33,346,9.537572
6,KIPP Soul Academy,761 - KIPP Soul Academy.xls,22,234,9.401709
7,Atlanta Neighborhood Charter - Middle,761 - Atlanta Neighborhood Charter - Middle.xls,45,504,8.928571
8,Herman J. Russell West End Academy,761 - Herman J. Russell West End Academy.xls,33,379,8.707124
9,Westside Atlanta Charter School,761 - Westside Atlanta Charter School.xls,10,115,8.695652
10,Booker T. Washington High School,761 - Booker T. Washington High School.xls,61,793,7.692308
11,B.E.S.T Academy,761 - B.E.S.T Academy.xls,21,282,7.446809
12,Woodson Park Academy School,761 - Woodson Park Academy School.xls,15,207,7.246377
13,Kipp Atlanta Collegiate Charter School,761 - Kipp Atlanta Collegiate Charter School.xls,42,645,6.511628
14,Maynard Jackson High School,761 - Maynard Jackson High School.xls,77,1223,6.295993
15,South Atlanta High School,761 - South Atlanta High School.xls,56,923,6.067172
16,Sylvan Hills Middle School,761 - Sylvan Hills Middle School.xls,24,397,6.045340
17,Kipp Strive Charter School,761 - Kipp Strive Charter School.xls,14,232,6.034483
18,KIPP VISION Charter School,761 - KIPP VISION Charter School.xls,14,238,5.882353
19,John Lewis Invictus Academy,761 - John Lewis Invictus Academy.xls,38,649,5.855162
20,KIPP WAYS Academy Charter School,761 - KIPP WAYS Academy Charter School.xls,17,297,5.723906
21,Martin L. King Jr. Middle School,761 - Martin L. King Jr. Middle School.xls,50,877,5.701254
22,Jean Childs Young Middle School,761 - Jean Childs Young Middle School.xls,29,509,5.697446
23,Wesley International Academy Charter,761 - Wesley International Academy Charter.xls,15,275,5.454545
24,David T Howard Middle School,761 - David T Howard Middle School.xls,49,909,5.390539
25,Hank Aaron New Beginnings Academy,761 - Hank Aaron New Beginnings Academy.xls,10,191,5.235602
26,Willis A. Sutton Middle School,761 - Willis A. Sutton Middle School.xls,70,1363,5.135730
27,Crawford Long Middle School,761 - Crawford Long Middle School.xls,31,608,5.098684
28,D. M. Therrell High School,761 - D. M. Therrell High School.xls,60,1198,5.008347
29,Frederick Douglass High School,761 - Frederick Douglass High School.xls,48,971,4.943357
30,Atlanta Classical Academy,761 - Atlanta Classical Academy.xls,36,748,4.812834
31,Benjamin E. Mays High School,761 - Benjamin E. Mays High School.xls,42,885,4.745763
32,Carver High School Early College,761 - Carver High School Early College.xls,23,503,4.572565
33,Midtown High School,761 - Midtown High School.xls,64,1424,4.494382
34,Ralph Bunche Middle School,761 - Ralph Bunche Middle School.xls,35,791,4.424779
35,Kindezi Old 4th Ward,761 - Kindezi Old 4th Ward.xls,4,93,4.301075
36,North Atlanta High School,761 - North Atlanta High School.xls,82,1947,4.211608
37,Carver High School,761 - Carver High School.xls,17,455,3.736264

In [ ]:
# filter for just Carver Cluster schools
carver_cluster = df[df["school"].isin(["Sylvan Hills Middle School", "Carver High School Early College", "Carver High School"])]
display(carver_cluster)

,school,file,housing_concern_count,total_students,percent_housing_concern
5,Carver High School,761 - Carver High School.xls,17,455,3.736264
6,Carver High School Early College,761 - Carver High School Early College.xls,23,503,4.572565
32,Sylvan Hills Middle School,761 - Sylvan Hills Middle School.xls,24,397,6.045340

In [14]:
cc_stress = pd.read_csv("../results/final_carver_cluster_stress_data.csv")
display(cc_stress)

,school,file,percent_school_work,percent_peer_problems,percent_social_media,percent_family_reasons,percent_bully,percent_school_grades,percent_partner_problems,percent_covid,percent_housing,percent_other,percent_none
0,Carver High School,761 - Carver High School.xls,37.362637,16.263736,9.670330,21.538462,3.076923,35.384615,12.527473,0.439560,3.736264,16.043956,38.681319
1,Carver High School Early College,761 - Carver High School Early College.xls,52.286282,15.308151,10.735586,26.043738,2.584493,40.357853,13.717694,2.186879,4.572565,14.910537,32.007952
2,Sylvan Hills Middle School,761 - Sylvan Hills Middle School.xls,45.591940,24.433249,12.090680,25.440806,8.060453,37.531486,13.853904,3.778338,6.045340,19.395466,31.234257

In [ ]:
percent_cols = [col for col in cc_stress.columns if col.startswith("percent_")]

for i, row in cc_stress.iterrows():
    school_name = row["school"]
    
    table = (
        row[percent_cols]
        .sort_values(ascending=False)
        .reset_index()
    )
    
    table.columns = ["category", "percent"]
    
    print(f"\n=== {school_name} ===")
    display(table)

=== Carver High School ===

                    category    percent
0               percent_none  38.681319
1        percent_school_work  37.362637
2      percent_school_grades  35.384615
3     percent_family_reasons  21.538462
4      percent_peer_problems  16.263736
5              percent_other  16.043956
6   percent_partner_problems  12.527473
7       percent_social_media    9.67033
8            percent_housing   3.736264
9              percent_bully   3.076923
10             percent_covid    0.43956

=== Carver High School Early College ===

                    category    percent
0        percent_school_work  52.286282
1      percent_school_grades  40.357853
2               percent_none  32.007952
3     percent_family_reasons  26.043738
4      percent_peer_problems  15.308151
5              percent_other  14.910537
6   percent_partner_problems  13.717694
7       percent_social_media  10.735586
8            percent_housing   4.572565
9              percent_bully   2.584493
10             percent_covid   2.186879

=== Sylvan Hills Middle School ===

                    category    percent
0        percent_school_work   45.59194
1      percent_school_grades  37.531486
2               percent_none  31.234257
3     percent_family_reasons  25.440806
4      percent_peer_problems  24.433249
5              percent_other  19.395466
6   percent_partner_problems  13.853904
7       percent_social_media   12.09068
8              percent_bully   8.060453
9            percent_housing    6.04534
10             percent_covid   3.778338