### Dataset Representation Check

In [1]:
import pandas as pd

In [8]:
school_list = pd.read_excel('../analysis/data/ncesdata_91F8F27D_cleaned.xlsx')
school_list.head()

,NCES School ID,State School ID,NCES District ID,State District ID,Low Grade,High Grade,School Name,District,County Name,Street Address,...,Locale,Charter,Students,Teachers,Student Teacher Ratio,Free Lunch,Reduced Lunch,Directly Certified,Type,Status
0,130012004145,GA-761-0415,1300120,GA-761,KG,12,Atlanta Classical Academy,Atlanta Public Schools,Fulton County,3260 Northside Dr NW,...,"City, Large",Yes,697.0,58.8,11.85,100.0,19.0,56.0,Regular,Open
1,130012002615,GA-761-0505,1300120,GA-761,KG,5,Atlanta Neighborhood Charter - Elementary,Atlanta Public Schools,Fulton County,688 Grant St SE,...,"City, Large",Yes,394.0,33.2,11.87,46.0,11.0,25.0,Regular,Open
2,130012003541,GA-761-0206,1300120,GA-761,06,8,Atlanta Neighborhood Charter - Middle,Atlanta Public Schools,Fulton County,820 Essie Ave SE,...,"City, Large",Yes,233.0,24.1,9.67,27.0,8.0,9.0,Regular,Open
3,130012003558,GA-761-1411,1300120,GA-761,06,12,B.E.S.T Academy,Atlanta Public Schools,Fulton County,1190 Northwest Dr NW,...,"City, Large",No,268.0,34.3,7.81,259.0,0.0,92.0,Regular,Open
4,130012000077,GA-761-5066,1300120,GA-761,PK,5,Barack and Michelle Obama Academy,Atlanta Public Schools,Fulton County,970 Martin St SE,...,"City, Large",No,297.0,25.2,11.79,297.0,0.0,145.0,Regular,Open

In [14]:
school_list_subset = school_list[(school_list["High Grade"]>5)]
display(school_list_subset)

,NCES School ID,State School ID,NCES District ID,State District ID,Low Grade,High Grade,School Name,District,County Name,Street Address,...,Locale,Charter,Students,Teachers,Student Teacher Ratio,Free Lunch,Reduced Lunch,Directly Certified,Type,Status
0,130012004145,GA-761-0415,1300120,GA-761,KG,12,Atlanta Classical Academy,Atlanta Public Schools,Fulton County,3260 Northside Dr NW,...,"City, Large",Yes,697.0,58.8,11.85,100.0,19.0,56.0,Regular,Open
2,130012003541,GA-761-0206,1300120,GA-761,06,8,Atlanta Neighborhood Charter - Middle,Atlanta Public Schools,Fulton County,820 Essie Ave SE,...,"City, Large",Yes,233.0,24.1,9.67,27.0,8.0,9.0,Regular,Open
3,130012003558,GA-761-1411,1300120,GA-761,06,12,B.E.S.T Academy,Atlanta Public Schools,Fulton County,1190 Northwest Dr NW,...,"City, Large",No,268.0,34.3,7.81,259.0,0.0,92.0,Regular,Open
7,130012001865,GA-761-0182,1300120,GA-761,09,12,Benjamin E. Mays High School,Atlanta Public Schools,Fulton County,3450 Benjamin E Mays Dr SW,...,"City, Large",No,1338.0,111.9,11.96,1338.0,0.0,526.0,Regular,Open
10,130012004174,GA-761-0315,1300120,GA-761,09,12,Booker T. Washington High School,Atlanta Public Schools,Fulton County,45 Whitehouse Dr SW,...,"City, Large",No,856.0,71.0,12.06,856.0,0.0,375.0,Regular,Open
12,130012004223,GA-761-1413,1300120,GA-761,09,12,Carver High School,Atlanta Public Schools,Fulton County,55 McDonough Blvd SE,...,"City, Large",No,544.0,40.8,13.33,544.0,0.0,260.0,Regular,Open
13,130012003540,GA-761-0106,1300120,GA-761,09,12,Carver High School Early College,Atlanta Public Schools,Fulton County,55 McDonough Blvd SE,...,"City, Large",No,514.0,56.6,9.08,514.0,0.0,219.0,Regular,Open
15,130012002290,GA-761-0199,1300120,GA-761,KG,8,Centennial Place Academy (Charter),Atlanta Public Schools,Fulton County,531 Luckie St NW,...,"City, Large",Yes,757.0,74.5,10.16,757.0,0.0,337.0,Regular,Open
16,130012004161,GA-761-0515,1300120,GA-761,06,12,Charles Drew Charter JA/SR Academy,Atlanta Public Schools,DeKalb County,300 E Lake Blvd SE,...,"City, Large",Yes,941.0,88.1,10.68,343.0,54.0,178.0,Regular,Open
21,130012003980,GA-761-1410,1300120,GA-761,06,12,Coretta Scott King Young Women's Leadership Ac...,Atlanta Public Schools,Fulton County,1190 Northwest Dr NW,...,"City, Large",No,377.0,47.7,7.90,369.0,0.0,145.0,Regular,Open
22,130012000017,GA-761-0173,1300120,GA-761,06,8,Crawford Long Middle School,Atlanta Public Schools,Fulton County,3200 Latona Dr SW,...,"City, Large",No,627.0,57.6,10.89,627.0,0.0,349.0,Regular,Open
23,130012004215,GA-761-1409,1300120,GA-761,09,12,D. M. Therrell High School,Atlanta Public Schools,Fulton County,3099 Panther Trl SW,...,"City, Large",No,964.0,68.4,14.09,964.0,0.0,349.0,Regular,Open
24,130012000027,GA-761-1563,1300120,GA-761,06,8,David T Howard Middle School,Atlanta Public Schools,Fulton County,551 John Wesley Dobbs,...,"City, Large",No,1073.0,70.5,15.22,228.0,24.0,144.0,Regular,Open
31,130012000089,GA-761-4058,1300120,GA-761,09,12,Frederick Douglass High School,Atlanta Public Schools,Fulton County,225 Hamilton E Holmes Dr NW,...,"City, Large",No,1296.0,86.6,14.97,1296.0,0.0,599.0,Regular,Open
33,130012002798,GA-761-0403,1300120,GA-761,06,12,Hank Aaron New Beginnings Academy,Atlanta Public Schools,Fulton County,2930 Forrest Hills Dr SW,...,"City, Large",No,147.0,37.0,3.97,147.0,0.0,100.0,Other/Alternative,Open
36,130012002344,GA-761-0100,1300120,GA-761,06,8,Herman J. Russell West End Academy,Atlanta Public Schools,Fulton County,765 Peeples St SW,...,"City, Large",No,342.0,38.8,8.81,342.0,0.0,199.0,Regular,Open
37,130012003660,GA-761-0207,1300120,GA-761,01,12,Hillside Conant School,Atlanta Public Schools,Fulton County,690 Courtenay Dr NE,...,"City, Large",No,67.0,10.0,6.70,64.0,0.0,64.0,Regular,Open
39,130012001866,GA-761-0282,1300120,GA-761,06,8,Jean Childs Young Middle School,Atlanta Public Schools,Fulton County,3116 Benjamin E Mays Dr SW,...,"City, Large",No,657.0,50.0,13.14,657.0,0.0,322.0,Regular,Open
40,130012004276,GA-761-1418,1300120,GA-761,06,8,John Lewis Invictus Academy,Atlanta Public Schools,Fulton County,1890 Donald Lee Hollowell Pkwy,...,"City, Large",No,692.0,59.5,11.63,692.0,0.0,388.0,Regular,Open
43,130012000060,GA-761-0288,1300120,GA-761,06,8,Judson Price Middle School,Atlanta Public Schools,Fulton County,1670 Benjamin Weldon Bickers,...,"City, Large",No,241.0,28.8,8.37,241.0,0.0,141.0,Regular,Open
44,130012004277,GA-761-1417,1300120,GA-761,KG,8,Kindezi Old 4th Ward,Atlanta Public Schools,Fulton County,1550 Hosea L Williams Dr NE,...,"City, Large",Yes,321.0,34.5,9.30,311.0,0.0,148.0,Regular,Open
45,130012004059,GA-761-0212,1300120,GA-761,09,12,Kipp Atlanta Collegiate Charter School,Atlanta Public Schools,Fulton County,98 Anderson Ave NW,...,"City, Large",Yes,874.0,69.7,12.54,874.0,0.0,287.0,Regular,Open
46,130012004395,GA-761-1422,1300120,GA-761,06,8,KIPP Soul Academy,Atlanta Public Schools,Fulton County,1445 Maynard Rd NW,...,"City, Large",Yes,285.0,22.3,12.78,285.0,0.0,179.0,Regular,Open
48,130012003823,GA-761-0115,1300120,GA-761,06,8,Kipp Strive Charter School,Atlanta Public Schools,Fulton County,1444 Lucile Ave SW,...,"City, Large",Yes,312.0,24.3,12.84,300.0,0.0,168.0,Regular,Open
50,130012003992,GA-761-0122,1300120,GA-761,06,8,KIPP VISION Charter School,Atlanta Public Schools,Fulton County,1820 Henry Thomas Dr SE,...,"City, Large",Yes,300.0,25.2,11.90,300.0,0.0,194.0,Regular,Open
52,130012003031,GA-761-0605,1300120,GA-761,06,8,KIPP WAYS Academy Charter School,Atlanta Public Schools,Fulton County,350 Temple St NW,...,"City, Large",Yes,289.0,22.6,12.79,289.0,0.0,199.0,Regular,Open
56,130012000025,GA-761-0373,1300120,GA-761,06,8,Martin L. King Jr. Middle School,Atlanta Public Schools,Fulton County,545 Hill St SE,...,"City, Large",No,879.0,65.1,13.50,856.0,0.0,352.0,Regular,Open
58,130012001939,GA-761-0186,1300120,GA-761,09,12,Maynard Jackson High School,Atlanta Public Schools,Fulton County,801 Glenwood Ave SE,...,"City, Large",No,1549.0,106.7,14.52,1267.0,0.0,408.0,Regular,Open
59,130012004237,GA-761-1414,1300120,GA-761,PK,8,Michael R. Hollis Innovation Academy,Atlanta Public Schools,Fulton County,225 James P. Brawley Drive NW,...,"City, Large",No,583.0,71.5,8.15,583.0,0.0,308.0,Regular,Open
60,130012000066,GA-761-4560,1300120,GA-761,09,12,Midtown High School,Atlanta Public Schools,Fulton County,929 Charles Allen Dr NE,...,"City, Large",No,1696.0,103.3,16.42,409.0,55.0,252.0,Regular,Open
64,130012002212,GA-761-0192,1300120,GA-761,09,12,North Atlanta High School,Atlanta Public Schools,Fulton County,4111 Northside Pkwy NW,...,"City, Large",No,2368.0,143.7,16.48,618.0,100.0,280.0,Regular,Open
69,130012000150,GA-761-0180,1300120,GA-761,06,8,Ralph Bunche Middle School,Atlanta Public Schools,Fulton County,1925 Niskey Lake Rd SW,...,"City, Large",No,651.0,53.2,12.24,651.0,0.0,323.0,Regular,Open
71,130012004240,GA-761-1412,1300120,GA-761,09,12,South Atlanta High School,Atlanta Public Schools,Fulton County,800 Hutchens Rd SE,...,"City, Large",No,942.0,50.8,18.54,941.0,0.0,424.0,Regular,Open
73,130012000058,GA-761-0188,1300120,GA-761,06,8,Sylvan Hills Middle School,Atlanta Public Schools,Fulton County,1461 Sylvan Rd SW,...,"City, Large",No,452.0,34.7,13.03,452.0,0.0,258.0,Regular,Open
76,130012004012,GA-761-0123,1300120,GA-761,KG,8,The Kindezi School,Atlanta Public Schools,Fulton County,286 Wilson Mill Rd SW,...,"City, Large",Yes,360.0,42.3,8.51,360.0,0.0,149.0,Regular,Open
80,130012003589,GA-761-1208,1300120,GA-761,KG,8,Wesley International Academy Charter,Atlanta Public Schools,Fulton County,211 Memorial Dr SE,...,"City, Large",Yes,776.0,57.1,13.59,748.0,0.0,259.0,Regular,Open
82,130012004139,GA-761-0314,1300120,GA-761,KG,8,Westside Atlanta Charter School,Atlanta Public Schools,Fulton County,1903 Drew Dr NW,...,"City, Large",Yes,349.0,33.4,10.45,161.0,30.0,96.0,Regular,Open
85,130012000107,GA-761-3067,1300120,GA-761,06,8,Willis A. Sutton Middle School,Atlanta Public Schools,Fulton County,2875 Northside Dr NW,...,"City, Large",No,1619.0,108.9,14.87,536.0,70.0,246.0,Regular,Open
86,130012004224,GA-761-1415,1300120,GA-761,PK,8,Woodson Park Academy School,Atlanta Public Schools,Fulton County,1605 Donald Lee Hollowell Pkwy,...,"City, Large",No,842.0,71.1,11.84,842.0,0.0,653.0,Regular,Open

In [ ]:
# get list of all schools in the APS district
# manual check against the kept_files.csv indicates exact matches except for 1 additional school in the APS district (Charles Drew Charter JA/SR Academy)
school_list_subset["School Name"]

0                             Atlanta Classical Academy
2                 Atlanta Neighborhood Charter - Middle
3                                       B.E.S.T Academy
7                          Benjamin E. Mays High School
10                     Booker T. Washington High School
12                                   Carver High School
13                     Carver High School Early College
15                   Centennial Place Academy (Charter)
16                   Charles Drew Charter JA/SR Academy
21    Coretta Scott King Young Women's Leadership Ac...
22                          Crawford Long Middle School
23                           D. M. Therrell High School
24                         David T Howard Middle School
31                       Frederick Douglass High School
33                    Hank Aaron New Beginnings Academy
36                   Herman J. Russell West End Academy
37                               Hillside Conant School
39                      Jean Childs Young Middle School
40                          John Lewis Invictus Academy
43                           Judson Price Middle School
44                                 Kindezi Old 4th Ward
45               Kipp Atlanta Collegiate Charter School
46                                    KIPP Soul Academy
48                           Kipp Strive Charter School
50                           KIPP VISION Charter School
52                     KIPP WAYS Academy Charter School
56                     Martin L. King Jr. Middle School
58                          Maynard Jackson High School
59                 Michael R. Hollis Innovation Academy
60                                  Midtown High School
64                            North Atlanta High School
69                           Ralph Bunche Middle School
71                            South Atlanta High School
73                           Sylvan Hills Middle School
76                                   The Kindezi School
80                 Wesley International Academy Charter
82                      Westside Atlanta Charter School
85                       Willis A. Sutton Middle School
86                          Woodson Park Academy School
Name: School Name, dtype: object